version: "3"
services:
  redis:
    image: redis
    container_name: redis-cache
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis:/usr/local/etc/redis
    expose:
      - 6379
  backend:
    build: ./backend
    volumes:
    - ./backend:/app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis-cache
    env_file:
      - environments/backend.env
    depends_on:
      - redis
    network_mode: "host"

  sidekiq:
    build: ./backend
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_URL=redis://redis-cache
    volumes:
      - ./backend:/app
      - /app/tmp
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
  frontend:
    build: ./frontend
    ports:
      - 5000:80
    depends_on:
      - backend
  phantom:
    image: wernight/phantomjs
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"
    ports: 
      - 8910:8910
    depends_on:
      - backend    